AddressBook/Controllers/PeopleController.cs
using AddressBook.Helpers;
using AddressBook.Services;
using AddressBook.ViewModels;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace AddressBook.Controllers
{
	[Authorize]
	public class PeopleController : Controller
	{
		private readonly IAddressBookService _svc;

		public PeopleController(IAddressBookService svc)
		{
			_svc = svc;
		}

		// GET: Contacts
		public async Task<ActionResult> Index()
		{
			var result = await _svc.GetFullContactList().ToPaged(1).ToListAsync();
			return View(result);
		}

		public ActionResult Create()
		{
			return View("Manage");
		}

		public async Task<ActionResult> Edit(int personId)
		{
			return View("Manage", await _svc.GetPerson(personId));
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Manage(Person person)
		{
			if (ModelState.IsValid)
			{
				await _svc.CreateOrUpdate(person);
				return RedirectToAction("Index");
			}
			return View();
		}

		[HttpPost]
		[Route("{id:int}")]
		public async Task<bool> Delete(int personId)
		{
			return await _svc.DeletePerson(personId);
		}

		public async Task<ActionResult> GetList(int page, string searchString = null)
		{
			var result = await _svc.GetFullContactList(searchString).ToPaged(page).ToListAsync();
			return result.Any() ? PartialView("_ListInner", result) : null;
		}

		protected override void Dispose(bool disposing)
		{
			_svc.Dispose();
			base.Dispose(disposing);
		}

	}
}

AddressBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - My ASP.NET Application</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")

</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				@Html.ActionLink("Address book", "Index", "People", new { area = "" }, new { @class = "navbar-brand" })
			</div>
			<div class="navbar-collapse collapse">
				
				@Html.Partial("_LoginPartial")
			</div>
		</div>
	</div>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p></p>
		</footer>
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>

AddressBook/Views/Shared/_LayoutList.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - My ASP.NET Application</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")

</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				@Html.ActionLink("Address book", "Index", "People", new { area = "" }, new { @class = "navbar-brand" })
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>
						<div class="searchBox input-group input-group-sm">
							@Html.TextBox("searchContact", null, new { @class = "form-control input-sm", aria_describedby = "search-addon", placeholder = "Search" })
							<span class="input-group-addon" id="search-addon">
								<span class="glyphicon glyphicon-search" aria-hidden="true"></span>
							</span>
						</div>
					</li>
					<li>
						@Html.ActionLink("Create contact", "Create", "People")
					</li>
				</ul>
				@Html.Partial("_LoginPartial")
			</div>
		</div>
	</div>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p></p>
		</footer>
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>

AddressBook/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
   <div class="container body-content">
        @RenderBody()
     </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>