AddressBook/Models/Contact.cs
using System;

namespace AddressBook.Models
{
	public class Contact
	{
		public int Id { get; private set; }
		public int PersonId { get; private set; }

		public string Address { get; private set; }
		public string Email { get; private set; }
		public string PhoneNumber { get; private set; }
		public Person Person { get; private set; }


		private Contact() { }

		public Contact(string address, string email, string phoneNumber, int personId)
		{
			Set(address, email, phoneNumber, personId);
		}

		public void Update(string address, string email, string phoneNumber)
		{
			Set(address, email, phoneNumber);
		}

		private void Set(string address, string email, string phoneNumber, int? personId = null)
		{
			if (string.IsNullOrEmpty(address) && string.IsNullOrEmpty(phoneNumber) && string.IsNullOrEmpty(email))
				throw new ArgumentNullException();
			Address = address;
			Email = email;
			PhoneNumber = phoneNumber;
			if (personId != null)
				PersonId = personId.Value;
		}
	}
}

AddressBook/ViewModels/Contact.cs
using System.ComponentModel.DataAnnotations;
using AddressBook.Helpers;

namespace AddressBook.ViewModels
{
	[DataAnnotationExtentions.AtLeastOnePropertyAttribute("Address", "Email", "PhoneNumber", ErrorMessage = "You must supply at least one value")]
	public class Contact
	{
		public int? Id { get; set; }

		public int PersonId { get; set; }

		[Display(Name = "Address")]
		public string Address { get; set; }

		[Display(Name = "Email")]
		[EmailAddress]
		public string Email { get; set; }

		[StringLength(16, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 3)]
		[Display(Name = "Phone")]
		[Phone]
		public string PhoneNumber { get; set; }
	}
}

AddressBook/Controllers/ContactsController.cs
using AddressBook.Services;
using AddressBook.ViewModels;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace AddressBook.Controllers
{
	[Authorize]
	public class ContactsController : Controller
	{
		private readonly IAddressBookService _svc;

		public ContactsController(IAddressBookService svc)
		{
			_svc = svc;
		}

		public ActionResult Create(int personId)
		{
			return View("Manage", new Contact { PersonId = personId });
		}

		public async Task<ActionResult> Edit(int contactId)
		{
			return View("Manage", await _svc.GetContact(contactId));
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Manage(Contact contact)
		{
			if (ModelState.IsValid)
			{
				await _svc.CreateOrUpdate(contact);
				return RedirectToAction("Index", "People");
			}
			return View();
		}

		[HttpPost]
		[Route("{id:int}")]
		public async Task<bool> Delete(int contactId)
		{
			return await _svc.DeleteContact(contactId);
		}

		protected override void Dispose(bool disposing)
		{
			_svc.Dispose();
			base.Dispose(disposing);
		}
	}
}

AddressBook/Views/Contacts/Manage.cshtml
@model AddressBook.ViewModels.Contact

@{
	ViewBag.Title = "Create";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Manage", "Contacts", FormMethod.Post, new { @class = "edit-form" }))
{
	@Html.AntiForgeryToken()
	@Html.HiddenFor(model => model.Id)
	@Html.HiddenFor(model => model.PersonId)
	<div class="form-horizontal">
		<hr />

		<div class="form-group">
			@Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<button class="btn btn-lg btn-primary btn-block" type="submit">Save</button>
			</div>
		</div>

		@Html.ValidationSummary(true, "", new { @class = "text-danger validation-errors" })
	</div>
}